// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanq1673PsZfUjh7iUWTdxaDLLKZBX0WU',
    appId: '1:948724176511:web:048faeb4f8c5f3dae0914a',
    messagingSenderId: '948724176511',
    projectId: 'recipebook-d538c',
    authDomain: 'recipebook-d538c.firebaseapp.com',
    storageBucket: 'recipebook-d538c.appspot.com',
    measurementId: 'G-J17TSXJCP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyygPN6wQQD_ON83uBTUlGWbIWaws0xoo',
    appId: '1:948724176511:android:d46c5be8fa195f9fe0914a',
    messagingSenderId: '948724176511',
    projectId: 'recipebook-d538c',
    storageBucket: 'recipebook-d538c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7AcXcDSGUbIeBJEPoggEHwj8rFzTBhs',
    appId: '1:948724176511:ios:61c8b402d0473046e0914a',
    messagingSenderId: '948724176511',
    projectId: 'recipebook-d538c',
    storageBucket: 'recipebook-d538c.appspot.com',
    iosBundleId: 'com.example.recipebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf7AcXcDSGUbIeBJEPoggEHwj8rFzTBhs',
    appId: '1:948724176511:ios:34dfd41657842035e0914a',
    messagingSenderId: '948724176511',
    projectId: 'recipebook-d538c',
    storageBucket: 'recipebook-d538c.appspot.com',
    iosBundleId: 'com.example.recipebook.RunnerTests',
  );
}
